### ISSUE TITLE
Implement conditional compilation basd on the Conditional Attribute

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#188]
More Information:

https://msdn.microsoft.com/en-us/library/system.diagnostics.conditionalattribute(v=vs.110).aspx

**Comment by Arakis** [comment]
Just added the attribute, so it can be used, but has not function yet. (8537ede8431379b0aea1e71fe65e1cc7c71efea6)

**Comment by charsleysa** [comment]
This attribute is picked up by the C# compiler so can cause issues.

It may be worth while letting the C# compiler do the work.

**Comment by Arakis** [comment]
Can you explain what you mean, please?

**Comment by charsleysa** [comment]
The C# compiler uses this attribute as well.

If we use this for removing Debug methods from Release then the work is already done for us by the C# compiler.

If we want to use this for other purposes then I would recommend creating our own attribute otherwise it is very easy to make a mistake and have the C# compiler remove a method without telling us.

**Comment by tgiphil** [comment]
If the C# compiler does this up front, then we have nothing to do.
