### ISSUE TITLE
Implementing Generics

### ISSUE THREAD

**Issue by charsleysa** [mosa/MOSA-Project#65]
@tgiphil @kiootic

I have been studying how generics work and I think I have come up with a solution that works just like the CLR runtime. 

Every time a generic is used we duplicate the entire tree and replace the generics with either a value type or a special reference pointer.

So when we encounter the instantiation of a generic we simply duplicate it's tree (if there already isn't a duplicate tree with that particular specific) and replace it by the type specified such as int, float, enum, and for reference types we just have a single version for all of them which just has special pointers to the objects. 

I think we can manage this through a few simple modifications of the existing type system and adding in a generic-to-specified duplicator which swaps out generics and adds in specifics and marks the duplicated tree as such. 

What do you guys think? 

I'm looking at starting development on this in July during my semester break.

**Comment by tgiphil** [comment]
In the short-term, the linker could maintain a hash of the binary code of the method. And upon a collision, each byte could be compared. If an exactly match is found, the methods are the same. The linker then only emits one of the methods and the other method(s) are re-directed to the address of the emitted method.

The upside of this short-term solution is that it's almost trivial to implement and immediately reduces code bloat due to generics (and possibly other simpler methods as well). The downside of this method is the compiler continue to do work that is later discarded that could have been avoided by an analysis of the generic type usages.
