### ISSUE TITLE
Provide nuget package that allows building and running directly from ide

### ISSUE THREAD

**Issue by Shadowblitz16** [mosa/MOSA-Project#834]
Can we have a nuget package that allows the following steps?

- install qemu
- install mosa nuget package
- build from ide's build button
- run from ide's run button and launches qemu

**Comment by tgiphil** [comment]
Please provide more information.

**Comment by AnErrupTion** [comment]
@Shadowblitz16 This will be possible when #972 is merged, since it includes a new nuspec file for Mosa.DeviceSystem. After that, you'll be able to install MOSA NuGet packages and use them as you would (of course, you would need to add a custom ``launchSettings.json`` file to run directly from the IDE for example)

**Comment by AnErrupTion** [comment]
@tgiphil @charsleysa This can be closed.
