### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by VoxelDeveloperDavid** [mosa/MOSA-Project#836]
hello i have a problem running the file compile.bat the log https://pastebin.com/q8XtxGiC
please help me

**Comment by tgiphil** [comment]
Here is the error message:

error MSB3821: The file "MainForm.resx" could not be processed because it is in Internet, or in the Restricted Website Zone, or has web markup. Remove the Webmark if you want to process these files.

See this web page for the solution:

https://thirtysix.zendesk.com/hc/en-us/articles/202921675-How-to-Unblock-a-File-Downloaded-from-an-Email-or-the-Internet?mobile_site=true

Target everything under:

C: \ Users\pogrammerX\Desktop\MOSA-Project-master
